{% set name = "napari-svg" %}
{% set version = "0.1.4" %}
{% set sha256 = "7e0cb5af0e98948cdc9719becec6c0641159444adf33b8b9ba538d0faee75b55" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools_scm
  run:
    - python >=3.6
    - imageio
    - napari-plugin-engine
    - numpy
    - vispy

test:
  imports:
    - napari_svg

about:
  home: https://github.com/napari/napari-svg
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: An io plugin for reading and writing svg files with napari
  doc_url: https://github.com/napari/napari-svg
  dev_url: https://github.com/napari/napari-svg
